import React,{useEffect,useState} from 'react';
import {View,Text,Pressable,StyleSheet,FlatList} from 'react-native';
import * as Location from 'expo-location';
import {api} from '../services/api';
export default function HospitalsScreen({route}){
  const params=route?.params||{}; const department=params.department||'내과'; const riskLevel=params.riskLevel||'routine'; const careContext=params.careContext||'';
  const[items,setItems]=useState([]);const[error,setError]=useState('');const[loading,setLoading]=useState(false);
  const search=async()=>{setError('');setLoading(true);try{const{status}=await Location.requestForegroundPermissionsAsync();if(status!=='granted')throw new Error('위치 권한이 필요합니다.');const loc=await Location.getCurrentPositionAsync({});const data=await api.searchHospitals({lat:loc.coords.latitude,lng:loc.coords.longitude,department,radiusKm:riskLevel==='emergency'?15:5,riskLevel,careContext});setItems(data.hospitals||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{if(params.department) search()},[params.department,params.careContext]);
  return <View style={s.wrap}><Text style={s.title}>주변 병원</Text><Text style={s.context}>진료과: {department}{careContext?` · ${careContext}`:''}</Text><Pressable style={s.btn} onPress={search} disabled={loading}><Text style={s.bt}>{loading?'검색 중...':'현재 위치로 병원 찾기'}</Text></Pressable>{!!error&&<Text style={s.err}>{error}</Text>}<FlatList data={items} keyExtractor={(x,i)=>x.ykiho||String(i)} ListEmptyComponent={!loading?<Text style={s.empty}>검색 결과가 아직 없습니다.</Text>:null} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name||item.yadmNm}</Text><Text style={s.meta}>{item.address||item.addr}</Text><Text style={s.meta}>거리 {item.distanceKm??'-'}km · 적합도 {item.matchScore??'-'}점</Text>{item.matchReasons?.length?<Text style={s.reason}>{item.matchReasons.join(' · ')}</Text>:null}</View>}/></View>}
const s=StyleSheet.create({wrap:{flex:1,padding:20,backgroundColor:'#F6F9FB'},title:{fontSize:24,fontWeight:'800',color:'#153B5A'},context:{fontSize:12,color:'#6F8190',marginTop:6},btn:{backgroundColor:'#1768A8',padding:14,borderRadius:12,alignItems:'center',marginVertical:14},bt:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#fff',padding:14,borderRadius:12,marginBottom:8},name:{fontWeight:'800',color:'#23465F'},meta:{fontSize:12,color:'#7A8A98',marginTop:4},reason:{fontSize:11,color:'#1768A8',marginTop:6},err:{color:'#B22D2D'},empty:{color:'#8A98A4',textAlign:'center',marginTop:24}})
